version: '3.9'

services:

  postgres:

    image: postgres:17

    container_name: academia-db

    restart: always

    environment:
      POSTGRES_DB: academia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:

    build: .

    container_name: academia-api

    restart: always

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/academia_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  pgadmin:

      image: dpage/pgadmin4

      container_name: academia-pgadmin

      restart: always

      depends_on:
        - postgres

      environment:
        PGADMIN_DEFAULT_EMAIL: admin@academia.com
        PGADMIN_DEFAULT_PASSWORD: admin123
        PGADMIN_LISTEN_PORT: 80

      ports:
        - "5050:80"

      volumes:
        - pgadmin_data:/var/lib/pgadmin

volumes:

  postgres_data:

  pgadmin_data: