CREATE TABLE pagamentos (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            matricula_id BIGINT NOT NULL,
                            valor NUMERIC(10, 2) NOT NULL,
                            status VARCHAR(30) NOT NULL,
                            gateway_id VARCHAR(255),
                            codigo_pix TEXT,
                            qr_code_base64 TEXT,
                            data_criacao TIMESTAMP,
                            pagamento TIMESTAMP,
                            expiracao TIMESTAMP,

                            CONSTRAINT fk_pagamentos_matricula
                                FOREIGN KEY (matricula_id)
                                    REFERENCES matriculas (id)
                                    ON DELETE RESTRICT
);

CREATE INDEX idx_pagamentos_matricula_id ON pagamentos(matricula_id);
CREATE INDEX idx_pagamentos_status ON pagamentos(status);